remote_theme: maxpowis/particle

# Site settings
title: Max Powis
description: I am a Solution architect & Data Engineer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Max Powis
user_description: 'I am a data engineer with deep functional and technical expertise in a wide range of data matters: data architecture, 
   data modeling, data integration, system integration, reference data management and business analytics.'
user_title: Data Expert
email: max@pow.is
twitter_username: maxpowis
github_username:  maxpowis

# Google-analytics
google-tag-manager:
  id: "GTM-MTGW8DM"

exclude: ['package.json', 'src' , 'node_modules']

collections:
  redirects:
    output: true

defaults:
  -
    scope:
      type: redirects
    values:
      layout: redirect
